#!/bin/sh

set -e

# Create the details.sv file with default or placeholder values
echo '{"APIKEY": "", "Collection": "", "Hdir": "", "last_fetch_timestamp": ""}' > /opt/GnomeWallpaperSetter/details.sv

chmod +x /usr/bin/GnomeWallpaperSetter
chmod -R 777 /opt/GnomeWallpaperSetter/
chown $USER:$USER /opt/GnomeWallpaperSetter/details.sv


exit 0
